
if [ -z "${choose_term_profile}" ]; then
	if [ -z "${SSH_TTY}" ]; then   #is not from ssh
	#	${SSH_CONNECTION} , ${SSH_CLIENT}
		nexttime=`php -f /home/bc/test/misc/is_day.php`
		if [ "${nexttime:0:1}" = "-" ]; then
			if [ "`xtermcontrol --get-bg`" != "rgb:ffff/ffff/ffff" ]; then
				#rgb:3030/0a0a/2424
				choose_term_profile=${nexttime} gnome-terminal --tab-with-profile=alb && exit
			fi
		else
			if [ "`xtermcontrol --get-bg`" = "rgb:ffff/ffff/ffff" ]; then
				choose_term_profile=${nexttime} gnome-terminal --tab-with-profile=negru && exit
			fi
		fi
		echo ${nexttime}
	fi
else
	echo ${choose_term_profile}
fi

uname -a
if [ -f /var/run/reboot-required ]; then echo 'reboot required'; fi

export PATH=/home/bc/.cargo/bin:/home/bc/Desktop/act:$PATH
export PYTHONPYCACHEPREFIX=/home/bc/pycache
export PYTHONPATH=$PYTHONPATH:
export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH

echo PYTHONPYCACHEPREFIX=${PYTHONPYCACHEPREFIX} PYTHONPATH=${PYTHONPATH} PKG_CONFIG_PATH=${PKG_CONFIG_PATH} PATH=${PATH}

alias gre='grep --color=auto -r --exclude-dir={.git,.pc,patches}'


#if set grep will stop working for example: echo a | grep a, is with -r will not search at stdin
#alias will list aliases and grep is 'grep --color=auto'

#PATh :/home/bc/.local/bin:/snap/bin is already
#doar act 26 poate upload_release_asset

#alias 'ls -l'
#xdotool sleep 1 key l s Return
#xdotool sleep 0.9 key f i n d KP_Space KP_Subtract n a m e KP_Space

#JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
#JRE_HOME=${JAVA_HOME}/jre
#LD_LIBRARY_PATH=${JRE_HOME}/lib/amd64
#PATH=${PATH}:${JAVA_HOME}/bin
#export JAVA_HOME
#export JRE_HOME
#export LD_LIBRARY_PATH
#export PATH
#echo ${JAVA_HOME}


#export LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatmoic.so.1.2.0

#vrea torra,meson
#export PATH=$PATH:/home/pi/.local/bin

#verlihub cauta aici
#export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
#cei cu pkg-config gtk4 vor
#export LD_LIBRARY_PATH=/usr/local/lib/arm-linux-gnueabihf:$LD_LIBRARY_PATH

#pentu pygobject care se uita la gobject-introspection ..local
#export PYTHONPATH=/usr/local/lib/python3.7/site-packages:$PYTHONPATH
#vrea pdb3 -m q.torra.main dar nu poate, asta si cu asta: din q pdb3 -m torra.main
#export PYTHONPATH=:$PYTHONPATH
#/usr/local/lib/python3/dist-packages:

#/home/bc/.local/lib/python3.10/site-packages:/home/bc/.local/lib/python3.10:/home/bc/.local/lib:/home/bc/.local
# PATH=${PATH}

#snap refresh --time

#a=`cat ~/bashrc_t`
#b=`stat -c %Y /var/log/apt/history.log`
#if ((a < b))
#then
#a=`cat /var/log/apt/history.log | grep upgrade`
#if [ -z "$a" ]
#then
#echo trebuie upgrade
#else
#echo nu trebuie upgrade
#fi
#date +%s > ~/bashrc_t
#fi
