#!/bin/bash

IFS=',' read -a format <<< "${storage}"

#u=${format[2]}
##a=`sudo fdisk -l | grep "^Disk ${format[0]}:" | tr -s ' ' | cut -d' ' -f5`
#a=`df -B${u} | grep "^${format[0]} " |  tr -s ' ' | cut -d' ' -f4`
#echo free: ${a}. free-margin: `echo ${a:0:-1}-${format[1]} | bc`${u}

last=${#format[@]}
last=$((last-1))
last=${format[${last}]}
unset format[-1]

for var in ${format[@]}; do
	x=( `df | grep "^${var} " |  tr -s ' '` ) #df $var is not good at nfs mounts

	b=${x[4]}
	avail_gb=$(echo "scale=2; ${x[3]} / 1048576" | bc)
	total_gb=$(echo "scale=2; ${x[1]} / 1048576" | bc)
	echo -n "${var} using: ${b} (${avail_gb}GB remaining)"

	if [ -z "${teststorage}" ]; then
		a=${x[1]}
	else
		a=${teststorage}
		aa=1000000;echo
	fi

	i=100
	while [ $a -gt 1000000 ]; do
		a=$((a/2))
		i=`echo "${i} * 0.${last}" | bc -l`

		if [ -n "${teststorage}" ]; then
			aa=$((2*aa))
			echo ${aa} ${i} `echo "${aa} * ($i/100)" | bc -l`
		fi
	done
	c=`echo "100 - ${i}" | bc`
	c=${c:0:5}
	echo -n ", max: ${c}%"

	b=${b:0:-1}
	echo -n ", "
	if (( $(echo "${b} > ${c}" |bc -l) )); then
		diff_pct=$(echo ${c} - ${b} | bc)
		diff_gb=$(echo "scale=2; (${diff_pct} / 100) * ${total_gb}" | bc)
		echo "NOT OK (${diff_gb}GB margin)"
	else
		diff_pct=$(echo ${c} - ${b} | bc)
		diff_gb=$(echo "scale=2; (${diff_pct} / 100) * ${total_gb}" | bc)
		echo "diff: ${diff_pct}% (${diff_gb}GB margin)"
	fi
done
