#!/usr/bin/env bash

#optional 1 file name

set -euo pipefail

. ~/test/game/base

upload_file() {
	file="$1"

	# all are files # [ -f "$file" ] || return

	sleep 1

	filename="$(basename "$file")"
	if [ -n "${NAME}" ]; then
		asset_name="${NAME}_${filename}"
	else
		asset_name="${filename}"
	fi

	echo "Uploading $filename as $asset_name"

	inter="$HOME/tmp/home/bc/activity/$asset_name" # --name in gh 2.46 is not

	# Symlink with the desired name
	cp -s "$file" "${inter}"

	echo "Uploading $asset_name"
	gh release upload "$TAG" "${inter}" --clobber || {
		rm "${inter}"
		exit 1
	}

	# Remove temp file
	rm "${inter}"
}

#gh release view "$TAG" --json assets --jq '.assets | length'
# Upload files
#if [ -n "${1:-}" ]; then , - is to not fail from set -u
if [ "$#" -gt 0 ]; then
	for file in "$@"; do
		upload_file "$CURRENT_DIR/${file}"
	done
else
	for file in "$CURRENT_DIR"/*; do
		upload_file "$file"
	done
fi
~/test/game/dif $TAG $HOME/$BASE
