#!/bin/sh
find ${1:-.} -type f -exec ls -lnq {} \+ | awk '
BEGIN {sum=0} # initialization for clarity and safety
function pp() {
#  u="+Ki+Mi+Gi+Ti+Pi+Ei";
#  split(u,unit,"+");
#  v=sum;
#  for(i=1;i<7;i++) {
#    if(v<1024) break;
#    v/=1024;
#  }
#  printf("%.3f %sB\n", v, unit[i]);
  printf("%lu B\n", sum);
}
{sum+=$5}
END{pp()}'
