# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generic.proto
# command: protoc --python_out=. generic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgeneric.proto\" \n\x04Root\x12\x18\n\x07items10\x18\n \x03(\x0b\x32\x07.Item10\"%\n\x06Item10\x12\x1b\n\x07\x66ield10\x18\n \x03(\x0b\x32\n.SubItem10\"+\n\tSubItem10\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\t\x12\x0e\n\x06\x66ield2\x18\x02 \x03(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generic_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROOT._serialized_start=17
  _ROOT._serialized_end=49
  _ITEM10._serialized_start=51
  _ITEM10._serialized_end=88
  _SUBITEM10._serialized_start=90
  _SUBITEM10._serialized_end=133
# @@protoc_insertion_point(module_scope)
