

const GST_CLOCK_TIME_NONE_lowhigh=-1


const GST_STATE_CHANGE_FAILURE=0
const GST_STATE_NULL=1
#const GST_STATE_READY=2
const GST_STATE_PLAYING=4

const GST_FORMAT_TIME=3

const GST_FLOW_OK=0

const GST_SECOND=1000*1000*1000



const GST_DISCOVERER_OK=0
const GST_DISCOVERER_URI_INVALID=1
const GST_DISCOVERER_ERROR=2
const GST_DISCOVERER_TIMEOUT=3
const GST_DISCOVERER_BUSY=4
const GST_DISCOVERER_MISSING_PLUGINS=5

const GST_ITERATOR_ERROR=3
