
if [ ! -e ~/no_term_profile ]; then
	if [ ! -e ~/choose_term_profile ]; then
		if [ -z "${skip_profile}" ]; then
			if [ -z "${SSH_TTY}" ]; then   #is not from ssh
			#	${SSH_CONNECTION} , ${SSH_CLIENT}
				~/test/startup/setcolors `php -f ${HOME}/test/startup/is_day.php` || exit
			fi
		else
			echo ${skip_profile}
		fi
	else
		cat ~/choose_term_profile
		rm ~/choose_term_profile
	fi
fi

if [ "${resizeterm}" != "" ]; then ~/test/startup/termsz; fi

uname -a
if [ -f /var/run/reboot-required ]; then echo 'reboot required'; fi

. ~/test/startup/exports

export PYTHONPATH=$PYTHONPATH: #for what? cd ~/t/torra-1; ./b : will do: ImportError: Error while finding module specification for 'torra.main' (ModuleNotFoundError: No module named 'torra')
export PYTHONPYCACHEPREFIX=~/pycache
echo PYTHONPYCACHEPREFIX=${PYTHONPYCACHEPREFIX} PYTHONPATH=${PYTHONPATH} PATH=${PATH}

source ~/aliases
