
if [ -z "${choose_term_profile}" ]; then
	if [ -z "${SSH_TTY}" ]; then   #is not from ssh
	#	${SSH_CONNECTION} , ${SSH_CLIENT}
		~/test/startup/setcolors || exit
	fi
else
	echo ${choose_term_profile} #[export] choose_term_profile= #or unset choose_term_profile #still new tab with same value
fi

if [ "${resizeterm}" != "" ]; then ~/test/startup/termsz; fi

uname -a
if [ -f /var/run/reboot-required ]; then echo 'reboot required'; fi

a=~/.local/bin
echo ${PATH} | grep -Fq "${a}"
if [ $? = 1 ]; then
	export PATH=${a}:$PATH
fi
export PATH=~/Desktop/act:$PATH
if [ "`uname -m`" != "x86_64" ]; then
	export PATH=${PATH}:~/x86_64
fi

export PYTHONPYCACHEPREFIX=~/pycache
export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH

export PYTHONPATH=$PYTHONPATH:
#for what? cd ~/t/torra-1; ./b : will do: ImportError: Error while finding module specification for 'torra.main' (ModuleNotFoundError: No module named 'torra')

echo PATH=${PATH} PYTHONPYCACHEPREFIX=${PYTHONPYCACHEPREFIX} PKG_CONFIG_PATH=${PKG_CONFIG_PATH} PYTHONPATH=${PYTHONPATH}

source ~/test/startup/aliases

~/test/startup/bookmark
