#!/bin/bash
# is_day.php(~/n/pat4) ~/maxmindif broadlink,(python3-cryptography)
#switch x to python on/off

#need to wait for the date sync, and date is writing in local but date -d don't understand except english
if [ -e ~/rememberevening ]; then
	d=`tail -n 1 ~/rememberevening | cut -d' ' -f2`
	while true; do
		da=`date +%d`
		echo ${d} ${da}
		if [ ${d} -ne ${da} ]; then break; fi
		sleep 10
	done
fi
~/test/act/a #ntp yes sync for same day restarts

#month of year
month=`date +%m`
if [ ${month:0:1} = 0 ]; then
	month=${month:1:1}
fi

t=( `cat ~/twitch` )
tm=$((month-1))
echo $((t[${tm}]/10)) $((t[${tm}]/8)) $((t[${tm}]/4)) $((t[${tm}]/2)) ${t[${tm}]} $((2*t[${tm}])) $((3*t[${tm}]))

amonth=6 #for northern hemisphere

dst=0
if perl -e 'exit ((localtime)[8])'; then #[8] is referring to $isdst from perl localtime list. test with perl -e 'print ((localtime)[8])'
	#winter time
	if [ ${month} -gt ${amonth} ]; then #only when the sun goes down
		dst=60
	fi
fi

#modulo against amonth
modulo=$((amonth-month))
modulo=${modulo#-}  #;echo ${modulo}

maximum=`cat ~/maxmindif` #99
part=30
maxmonths=$((maximum/part))

if [ ${maxmonths} -gt ${modulo} ]; then
#cut from the day
	dif=$(((maxmonths-modulo)*part))
	echo dif=${dif}
else
	dif=0
fi

#from_sun () { #on android where on standby will not work in background
a=`php -f ~/test/startup/is_day.php`
remaining1=${a%%_*}

if [ -e ~/fixedtime ]; then #example: 18:00
	then=$(date -d "$(cat ~/fixedtime)" +%s)
	now=`date +%s`
	remaining2=$((then-now))
	remaining2=$((remaining2/60))
else
	remaining2=0
fi
echo -n remaining1\(${remaining1}\)-dif\(${dif}\)+dst\(${dst}\)
remaining=$((remaining1-dif+dst))

echo =${remaining} or fixedremaining\(${remaining2}\)
if [ ${remaining2} -gt ${remaining} ]; then
	remaining=${remaining2}
fi

while [ ${remaining} -ge 0 ]; do #on standby will not decrement, but that was on android tablet
	echo ${remaining}
	sleep 1m
	remaining=$((remaining-1))
done
echo done

if [ -n "${switch}" ]; then
	python ~/test/plug/on.py
fi

if [ -e ~/rememberevening ]; then
	tail -n 1 ~/rememberevening
	date | tee -a ~/rememberevening
else date; fi

if [ -n "${switch}" ]; then
	echo Enter for off
	read
	python ~/test/plug/off.py
fi

#in .config/lxsession/LXDE-pi/autostart

#@lxpanel --profile LXDE-pi
#@pcmanfm --desktop --profile LXDE-pi
#@lxterminal -e /home/bc/test/startup/evening
