
on:
 workflow_dispatch:

jobs:
 dbuild:
  runs-on: ubuntu-22.04 #libssl3 is not at impish
  steps:
   - uses: actions/checkout@v3
     with:
      path: in
   - name: Run a multi-line script
     run: |
      if [ -z "`dpkg -s devscripts>/dev/null 2>&1 && echo x`" ]; then
       sudo apt install -y devscripts debhelper
      fi
      name=`cat in/debian/changelog | head -1 | grep -o ^[^\ ]*`
      origf=${name}-1.tar.gz
      if [ ! -e "${origf}" ]; then
       origln=${name}_1.orig.tar.gz
       wget https://ppa.launchpadcontent.net/colin-i/ppa/ubuntu/pool/main/e/${name}/${origln} -O ${origf}
       ln -s ${origf} ${origln}
      fi
      cd in
      debuild -S -us -uc
   - name: unsigned debs
     uses: actions/upload-artifact@v3
     with:
      name: sdebs
      path: |
       ./*.dsc
       ./*.changes
       ./*.buildinfo
       ./*.debian.tar.xz
