#!/bin/bash

#sudo gem install twurl
#twurl authorize --consumer-key `cat ~/n/pat6` \
#                --consumer-secret `cat ~/n/pat7`

#or
#npm
#./xurl auth oauth1  --consumer-key `cat ~/n/pat6` --consumer-secret `cat ~/n/pat7` --access-token `cat ~/n/pat15` --token-secret `cat ~/n/pat16`
#npm install @xdevplatform/xurl

#text=`twurl /2/users/me?expansions=pinned_tweet_id | jq ".includes.tweets[0].text"`
#\&tweet.fields=text        history,id and text are always
#-t to see response headers
#x-app-limit-24hour-reset
id=$(/home/bc/Desktop/npm/node_modules/.bin/xurl "/2/users/me?user.fields=pinned_tweet_id" | jq -r '.data.pinned_tweet_id')

if [ -n "${inter}" ]; then
	echo ${id}
	read
fi

text=$(curl -sL "https://x.com/flashixy/status/${id}" | tr -d '\0')

if [ -n "${inter}" ]; then
	echo ${text}
	read
fi

text=$(printf '%s\n' "$text" | grep -oP 'full_text:"\K([^"]|\\")*')

if [ -n "${inter}" ]; then
	echo ${text}
	read
fi

text=$(echo ${text} | python3 -c 'import sys,codecs,html; print(html.unescape(codecs.decode(sys.stdin.read(),"unicode_escape")))')

n=`echo ${text} | grep -Poe "[^ ]*(?:.(?! rows))+$" | grep -Poe "[^ ]*" | head -1`
k=`echo ${n}/1000 | bc`
echo -n ${k}`cat ~/number_precision`
