#!/bin/bash

#python -m b.b there, ./a here
#space is pause, q quit, else new zone

#IFS='\n' a=`cat /proc/stat`
a=( `cat /proc/stat | head -1` )
n=${#a[@]}
sum=0
for ((i = 1; i < ${n}; i++ )); do
	sum=$((sum+a[$i]))
done
activ=$((sum-a[4]))

python aa.py 0

while :; do
	sleep 10

	a=( `cat /proc/stat | head -1` )
	n=${#a[@]}
	sum_new=0
	for ((i = 1; i < ${n}; i++ )); do
		sum_new=$((sum_new+a[$i]))
	done
	activ_new=$((sum_new-a[4]))

	sdif=$((sum_new-sum))
	adif=$((activ_new-activ))
	x=$((100*adif/sdif))

	python a.py ${x} || exit 1

	activ=${activ_new}
	sum=${sum_new}
done
