
#name: appimage

on:
 # Triggers the workflow on push or pull request events but only for the main branch
 #push:
 # branches: [ main ]
 #pull_request:
 # branches: [ main ]
 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a single job called "build"
 rbuild:
  # The type of runner that the job will run on
  runs-on: ubuntu-18.04
  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
   - name: Run a multi-line script
     run: |
      #get the version from changelog/launchpad/input
   - name: Create Release
     id: create_release
     uses: actions/create-release@v1
     env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
     with:
      tag_name: ${{ env.version }}
      release_name: Release ${{ env.version }}
      draft: false
      prerelease: false
   - name: Store upload url for assets
     run: |
      #store at id=67484178
