on:
 workflow_dispatch:

jobs:
 dbuild:
  runs-on: ubuntu-24.04-arm
  steps:
   - uses: actions/checkout@v4
   - name: Run a multi-line script
     run: |
      cd docker/rufflebld
      ../make
      cd ../..
      mv ~/.cargo/bin/ruffle_desktop .
      echo "filepath=./ruffle_desktop" >> $GITHUB_ENV
   - name: artifact
     uses: actions/upload-artifact@v4
     with:
      name: release
      path: ${{ env.filepath }}
