on:
 workflow_dispatch:

jobs:
 del:
  runs-on: ubuntu-22.04
  steps:
   - name: Remove asset
     uses: mknejp/delete-release-assets@v1
     with:
      token: ${{ secrets.PAT }}
      tag: refs/tags/${{ env.tag }}
      assets: ${{ env.file }}
